plugins {
    id 'java'
}

allprojects {
    group = 'dev.mimi.woodcutter'
    version = '1.0.1'
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of((findProperty('java_version') ?: '21') as int)
        }
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = (findProperty('java_version') ?: '21') as int
    }
}
