pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://repo.papermc.io/repository/maven-public/" }
    }
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.PREFER_PROJECT
    repositories {
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://repo.papermc.io/repository/maven-public/" }
    }
}

rootProject.name = "woodcutter"

include("common", "paper", "fabric")
